# Generated by Django 5.2.11 on 2026-03-20 21:08

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('avatar_data_url', models.TextField(blank=True, default='')),
                ('preferences', models.JSONField(default=accounts.models.default_preferences)),
                ('watchlist', models.JSONField(default=accounts.models.default_watchlist)),
                ('company_tags', models.JSONField(default=dict)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
    ]
